name: Backend workflow

#Triggers on demand and pull request with changes on main.
on:
  workflow_dispatch:
  push:
    pull-request:
      types:
        - opened
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Setup python
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: latest

      - name: Install dependencies
        run: cd starter/backend && pip install pipenv && pipenv install

      - name: Run the linter
        run: cd starter/backend && pipenv run lint

      - name: Run the test
        run: cd cd starter/backend && pipenv run test 
        
      - name: Building the app with Docker
        run: echo "Working so far"

