name: Frontend Continuous Integration

#Triggers on demand and pull request with changes on main.
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies on package.json
        run: cd starter/frontend && npm ci

      - name: Run the linter
        run: cd starter/frontend && npm run lint -- --fix

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies on package.json
        run: cd starter/frontend && npm ci

      - name: Run the test
        run: cd starter/frontend && CI=true npm test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies on package.json
        run: cd starter/frontend && npm ci

      - name: Run the test
        run: cd starter/frontend && CI=true npm test

      - name: Building the app with Docker
        run: |
          cd starter/frontend
          #build the image
          docker build -t backend_image:latest
          docker build --build-arg=$REACT_APP_MOVIE_API_URL --tag=frontend_image:${{ github.sha }} .
          #Running the container
          docker run --name frontend_container -p 3000:3000 -d frontend_image:${{ github.sha }}

      - name: Building the kurbernetes manifest
        run: |
          cd starter/frontend/k8s
          #aws eks update-kubeconfig

          kustomize edit set image frontend=$ECR_URL:$GITHUB_SHA

          kustomize build | kubectl apply -f -