name: Frontend workflow

#Triggers on demand and pull request with changes on main.
on:
  workflow_dispatch:
  push:
    pull-request:
      types:
        - opened
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies on package.json
        run: cd starter/frontend && npm ci
        
      - name: Run the test
        run: cd starter/frontend && CI=true npm test

      - name: Run the linter
        run: cd starter/frontend && npm run lint
        
      - name: Building the app with Docker
        run: |
          cd starter/frontend
          npm ci
          REACT_APP_MOVIE_API_URL=http://localhost:5000 npm start