name: Pulling image from AWS

on:
  workflow_dispatch:


jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: AWS Credentials config
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets. AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login ECR aws
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: project_cicd/final_project
          IMAGE_TAG: a6d641fa3a30d984c6fa82d3edecd550f589c6da
        run: |
          docker pull $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
